-- PRINTER MANAGER (2026-09-15): printer lifecycle audit actions reported by
-- the CT40 print bridge. Additive enum values; safe on PG 12+.
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRINTER_ADDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRINTER_CONNECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRINTER_DISCONNECTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRINTER_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRINTER_TEST_PRINTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRINTER_CONFIGURATION_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRINT_FAILED';
