import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams } from 'react-router-dom';
import type { DisplaySnapshot } from './display-view';
import { relativeTime, viewState } from './display-view';

/**
 * Station Display page (owner order 2026-09-16) — /display/:token
 * READ-ONLY live view for any browser screen (PC / TV / tablet).
 * Transport: native EventSource (auto-reconnect) + a 10s snapshot poll that
 * self-heals anything a missed event could leave stale. No auth, no write
 * path, no operational buttons — only Enter Fullscreen (§22).
 */

const API_BASE = (import.meta.env.VITE_API_BASE || '/api').replace(/\/$/, '');

const STATE_TEXT: Record<string, { label: string; color: string }> = {
  IDLE: { label: 'WAITING FOR NEXT OPERATION', color: '#8aa0b4' },
  PROCESSING: { label: 'PROCESSING…', color: '#4da3ff' },
  SUCCESS: { label: '✓ CONFIRMED', color: '#39d98a' },
  ERROR: { label: '✕ ERROR', color: '#ff5d5d' },
};

export default function StationDisplay() {
  const { token = '' } = useParams();
  const [snap, setSnap] = useState<DisplaySnapshot | null>(null);
  const [fatal, setFatal] = useState<'NOT_FOUND' | null>(null);
  const [live, setLive] = useState(false); // stream connected
  const [clock, setClock] = useState(() => Date.now());
  const rootRef = useRef<HTMLDivElement>(null);

  const poll = useCallback(async () => {
    try {
      const r = await fetch(`${API_BASE}/v1/display-views/${token}`, { cache: 'no-store' });
      if (r.status === 404) { setFatal('NOT_FOUND'); return; }
      if (!r.ok) return;
      setSnap((await r.json()) as DisplaySnapshot);
    } catch { /* offline — the banner shows; keep polling */ }
  }, [token]);

  useEffect(() => { void poll(); }, [poll]);

  // SSE stream + self-healing poll + 1s clock for the relative timestamps.
  useEffect(() => {
    const es = new EventSource(`${API_BASE}/v1/display-views/${token}/stream`);
    es.addEventListener('snapshot', (ev) => {
      try { setSnap(JSON.parse((ev as MessageEvent).data)); } catch { /* ignore */ }
    });
    es.onopen = () => setLive(true);
    es.onerror = () => setLive(false);
    const fallback = setInterval(() => { if (!live) void poll(); }, 10_000);
    const tick = setInterval(() => setClock(Date.now()), 1_000);
    return () => { es.close(); clearInterval(fallback); clearInterval(tick); };
  }, [token, live, poll]);

  async function goFullscreen() {
    try {
      if (document.fullscreenElement) await document.exitFullscreen();
      else await rootRef.current?.requestFullscreen();
    } catch { /* browser refused — button stays for another tap */ }
  }

  if (fatal === 'NOT_FOUND') {
    return (
      <div style={{ ...wrap, justifyContent: 'center' }}>
        <div style={{ ...big(28), color: '#ff5d5d' }}>Display not found</div>
        <div style={mid}>This display URL is invalid or was regenerated by the admin.</div>
      </div>
    );
  }

  const state = viewState(snap, clock);
  const st = STATE_TEXT[state] ?? STATE_TEXT.IDLE;
  const scan = snap?.lastScan ?? null;
  const progress = snap?.progress ?? null;
  const pct = progress && progress.total > 0 ? Math.min(100, Math.round((progress.done / progress.total) * 100)) : 0;

  return (
    <div ref={rootRef} style={{ ...wrap, justifyContent: 'space-between' }} data-testid="station-display">
      {/* header: station + live/offline pill (§23) */}
      <header style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 24 }}>
        <div>
          <div style={{ ...big(64, 800), letterSpacing: 2 }}>{(snap?.station?.name ?? snap?.display?.name ?? '…').toUpperCase()}</div>
          {snap?.station?.code && <div style={{ ...mid, opacity: 0.7 }}>{snap.station.code} · {snap.station.department}</div>}
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 8 }}>
          <span style={{
            fontSize: 26, fontWeight: 700, padding: '6px 22px', borderRadius: 999,
            background: live ? 'rgba(57,217,138,.15)' : 'rgba(255,157,0,.18)',
            color: live ? '#39d98a' : '#ff9d00', border: `2px solid ${live ? '#39d98a55' : '#ff9d0055'}`,
          }} data-testid="connection-pill">
            {live ? '🟢 LIVE' : '🟠 RECONNECTING'}
          </span>
          {!live && <span style={{ ...mid, color: '#ff9d00' }}>Connection lost — reconnecting…</span>}
        </div>
      </header>

      {/* body */}
      <main style={{ display: 'flex', flexDirection: 'column', gap: 28, alignItems: 'center', textAlign: 'center' }}>
        {snap?.enabled === false ? (
          <div style={{ ...big(40), color: '#8aa0b4' }}>Display disabled by admin</div>
        ) : (
          <>
            {snap?.worker && (
              <div style={{ ...mid, fontSize: 40 }}>Worker: <b>{snap.worker.code}</b>{snap.worker.name ? ` · ${snap.worker.name}` : ''}</div>
            )}
            {snap?.task && <div style={{ ...mid, fontSize: 40 }}>Task: {snap.task.title}</div>}
            {snap?.operation && (
              <div style={{ ...mid, opacity: 0.8 }}>
                {snap.operation.label}{snap.operation.sessionCode ? ` · ${snap.operation.sessionCode}` : ''}
                {snap.operation.sessionStatus ? ` (${snap.operation.sessionStatus})` : ''}
              </div>
            )}

            {scan ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                <div style={{ ...big(120, 800), letterSpacing: 4 }} data-testid="last-scan-code">
                  {scan.code ?? scan.productName ?? scan.kind}
                </div>
                <div style={{ ...mid, fontSize: 40 }}>
                  {scan.kind}
                  {snap?.customer && <span> · {snap.customer}</span>}
                  {typeof scan.quantity === 'number' && <span> · Qty {scan.quantity}</span>}
                </div>
              </div>
            ) : (
              <div style={{ ...big(56, 700), color: '#8aa0b4' }}>No scans yet</div>
            )}

            <div style={{ ...big(72, 800), color: st.color }} data-testid="state-line">{st.label}</div>
            {snap?.error && (
              <div style={{ ...mid, color: '#ff5d5d', fontSize: 34 }}>
                {snap.error.type}{snap.error.reason ? ` — ${snap.error.reason}` : ''}
              </div>
            )}

            {progress && (
              <div style={{ width: 'min(80vw, 900px)', display: 'flex', flexDirection: 'column', gap: 10 }}>
                <div style={{ height: 34, borderRadius: 999, background: '#1c2733', overflow: 'hidden' }}>
                  <div style={{ width: `${pct}%`, height: '100%', background: 'linear-gradient(90deg,#2f9dff,#39d98a)' }} />
                </div>
                <div style={{ ...mid, fontSize: 38 }}>
                  {progress.done} / {progress.total} {progress.label ?? ''}
                </div>
              </div>
            )}
          </>
        )}
      </main>

      {/* footer: fullscreen + last update (§22) */}
      <footer style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <button onClick={goFullscreen} style={fsBtn}>⛶ Enter Fullscreen</button>
        <div style={{ ...mid, opacity: 0.7 }}>
          Last update: {relativeTime(snap?.lastUpdate, clock)}
        </div>
      </footer>
    </div>
  );
}

const wrap: React.CSSProperties = {
  position: 'fixed', inset: 0, zIndex: 50,
  display: 'flex', flexDirection: 'column',
  padding: 'min(5vh, 48px) min(6vw, 72px)',
  background: '#0b1118', color: '#eef4fa',
  fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  gap: 20,
};

function big(size: number, weight = 700): React.CSSProperties {
  return { fontSize: size, fontWeight: weight, lineHeight: 1.1, margin: 0 };
}

const mid: React.CSSProperties = { fontSize: 28, fontWeight: 500, opacity: 0.9 };

const fsBtn: React.CSSProperties = {
  fontSize: 22, fontWeight: 600, padding: '10px 26px', borderRadius: 12,
  background: '#16222e', color: '#cfe3f5', border: '2px solid #2a3b4d', cursor: 'pointer',
};
